version: '3.3'

volumes:
    logs:
        driver: local
    mysqldata:
        driver: local

services:
    api:
        build: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysqldata:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080
